### ISSUE TITLE
How does company router install packerbeat?

### ISSUE THREAD

**Issue by Iateautumn** [fkie-cad/socbed#92]
Hi

I want to install new application in hosts, however it seems that there is no any dns configuration in all host of socbed, which means they are not capable to resolve any domain name, but how does this ansible script work:
```
- name: Download packetbeat to /tmp
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/packetbeat/{{ packetbeat_name }}.tar.gz"
    dest: "/tmp"
  retries: 2
  register: result
  until: result is succeeded
```
by the way, I find that the gateway of internet router disappear sometimes， do you have any idea of this?

if my memory serves me right, all hosts can visit external network by ip instead of domain because internet router have a network interface which is nat mode, and none of them configure dns right?

thanks
